[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'npm cache clean --force',
  'rm -rf node_modules package-lock.json',
  'npm install --legacy-peer-deps --no-audit'
]

[phases.build]
cmds = [
  'export CI=false',
  'npm run build'
]

[start]
cmd = 'npx serve -s build -l $PORT'
