version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: iware-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: IwareSecure2026!@#
      MYSQL_DATABASE: iware_perizinan
      MYSQL_USER: iware
      MYSQL_PASSWORD: IwareDB2026!@#
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - iware-network
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build: ./backend
    container_name: iware-backend
    restart: always
    environment:
      PORT: 5000
      NODE_ENV: production
      DB_HOST: mysql
      DB_USER: iware
      DB_PASSWORD: IwareDB2026!@#
      DB_NAME: iware_perizinan
      JWT_SECRET: d73d71a47452c7af78f6bd888005afee23adba5f936da33d67ce5baed764db62
      FRONTEND_URL: https://www.iwareid.com
      WHATSAPP_ENABLED: false
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - iware-network

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: https://www.iwareid.com/api
    container_name: iware-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - iware-network

volumes:
  mysql_data:

networks:
  iware-network:
    driver: bridge
